name: branch
'on':
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - uses: actions/cache@v1
        with:
          path: Pods
          key: '${{ runner.os }}-pods-${{ hashFiles(''**/Podfile.lock'') }}'
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: fastlane run_all_but_deploy
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: run_all_but_deploy
          skip-tracking: false

